### ISSUE TITLE
Help translate TurboWarp

### ISSUE THREAD

**Issue by GarboMuffin** [TurboWarp/translations#1]
# Currently On Hold

We're looking for people who are fluent in English and at least one other language to help translate TurboWarp into languages other than English.

If you're interested, please read the [contributing guidelines](https://github.com/TurboWarp/translations/blob/master/CONTRIBUTING.md) to learn how to contribute. Comment here or open an issue if you have questions.

Thank you!

**Comment by Dieforrobux** [comment]
What do you mean?

**Comment by Dieforrobux** [comment]
50 Followers? What do we do here. How do we help translate turbowarp?

**Comment by Dieforrobux** [comment]
Maybe top 50 people

**Comment by GarboMuffin** [comment]
The problem right now is that these messages only exist in English:

![image](https://user-images.githubusercontent.com/33787854/98450640-ce053b80-2103-11eb-9f5f-6f1f96c28bf5.png)

![image](https://user-images.githubusercontent.com/33787854/98450641-d2315900-2103-11eb-8000-4ccdb60c2387.png)

I want to crowdsource translations so that these messages can be displayed in a user's preferred language.

**Comment by Dieforrobux** [comment]
Oh Ok.

**Comment by Dieforrobux** [comment]
Can my parents help?(My parents are fluent in ghana langaue)sorry for mis-spelling

**Comment by Dieforrobux** [comment]
Ok i get it

**Comment by Dieforrobux** [comment]
_K i will try to get people who use turbowarp and are fluent at different lanaguages to come here._

**Comment by Dieforrobux** [comment]
I Put in on my scratch account https://scratch.mit.edu/users/dieforrobux/

**Comment by jemunm378** [comment]
I can probably help.
I know some Spanish.

**Comment by IXCGITHUB** [comment]
I am fluent in english and dutch. (nederlands)

**Comment by IXCGITHUB** [comment]
My scratch account is IXC

**Comment by StudioChew** [comment]
i can speak finnish, maybe i can help?

**Comment by rofdo** [comment]
I speak german.

**Comment by TheNumber100IsTaken** [comment]
i can speak norwegian maybe i can help

**Comment by sirokurokumasan** [comment]
I am Japanese, maybe I can help.

**Comment by Dieforrobux** [comment]
Ok, GarboMuffin Will Talk with you later.

_____

Lets help turbowarp!

**Comment by sfederici** [comment]
I can do it for Italian

**Comment by Protostar-2007** [comment]
hi! I can help you with Hindi

**Comment by Jordanjopa1** [comment]
I can help with Italian so much! What i/you need? (Note: I am Italian)

**Comment by Jordanjopa1** [comment]
I will put the translations in a Scratch project or an HTML file. And i will take a long time... but i can do it 🥳

**Comment by Jordanjopa1** [comment]
@GarboMuffin

**Comment by GarboMuffin** [comment]
If you want to contribute please read https://github.com/TurboWarp/translations/blob/master/CONTRIBUTING.md

**Comment by Jordanjopa1** [comment]
@GarboMuffin i read it

**Comment by Jordanjopa1** [comment]
But (sorry) i need to try aother method (unfortunately).

**Comment by Dieforrobux** [comment]
> I will put the translations in a Scratch project or an HTML file. And i will take a long time... but i can do it 🥳

kk

**Comment by Jordanjopa1** [comment]
@GarboMuffin i will finish it tomorrow. I used Google to translate BUT i fixe ALL the problems in the translitions, i'm sure that the translition doesn't have any problems...

**Comment by Dieforrobux** [comment]
Ok.

**Comment by Mayank-1234-cmd** [comment]
I can help with hindi!

**Comment by AnnoyedArt1256** [comment]
I can help with Turkish!

**Comment by Dieforrobux** [comment]
If you cam help

____

Great!

**Comment by Dieforrobux** [comment]
*can*

**Comment by Dieforrobux** [comment]
*can

**Comment by GarboMuffin** [comment]
A couple reminders:

 - you have to submit a pull request after forking and committing changes
 - you can unsubscribe from GitHub issues if you don't want to get spammed with notifications/emails (I won't be surprised if this issue gets an influx of comments tomorrow morning)
 - do not use google translate. we want high quality translations from fluent (preferably native) speakers, not from a computer

**Comment by Mr-Anonymous75** [comment]
Not to boast, but I consider myself extremely fluent in English - even more than I am in my mother tongue, Hindi (not that I'm bad in that, though). So can I help in translating to Hindi?

**Comment by Mr-Anonymous75** [comment]
> Not to boast, but I consider myself extremely fluent in English - even more than I am in my mother tongue, Hindi (not that I'm bad in that, though). So can I help in translating to Hindi?

Nevermind, I just realized that Hindi isn't there in these languages (and it isn't in the Scratch languages either).

**Comment by PhilipStudios** [comment]
Hello! I am fluent in English, German, and Bulgarian. I can help. My Scratch username is Philipuss.

**Comment by PhilipStudios** [comment]
So, I translated the half into German. How shall I share the fork and I am not exactly aware if I am actually saving the changes I make. CTRL+S doesn't work and I can't see a save button or a message saying "saved"... When I edit de.yaml, does it save automatically?

**Comment by EBXavier** [comment]
GarboMuffin, I'm pretty good at English and my mother language is Portuguese. I can help!

**Comment by Dieforrobux** [comment]
@GarboMuffin Will Come and repond soon

_____

You have to wait 😔

**Comment by Dieforrobux** [comment]
### _**Scratch Account**_
> My Scratch Account is IXC
____
Its not about scratch accounts and stuff. But you can post your scratch account for some kind of reason. I Posted it for a good reason To show my followers that will look at my shared projects and see i need people to check it out and Check it out to see people have known that they might help us out.

**Comment by igorex95** [comment]
> We're looking for people who are fluent in English and at least one other language to help translate TurboWarp into languages other than English.
> 
> If you're interested, please read the [contributing guidelines](https://github.com/TurboWarp/translations/blob/master/CONTRIBUTING.md) to learn how to contribute. Comment here or open an issue if you have questions.
> 
> Thank you!
I can help translate it to Polish, because i am from Poland

**Comment by Wilamaxin** [comment]
I can help to translate it into the Polish language

**Comment by lambodhar17** [comment]
I guess that you could have used google translate

**Comment by Jordanjopa1** [comment]
@GarboMuffin https://scratch.mit.edu/projects/446888444 < ALL the translition here
Loading screen ⬇

Loading scripts: Caricamento degli script
This may take a wile...: Ci vorrà un po di tempo...
Troubleshooting: Risoluzione dei problemi

**Comment by PizzasAreGreat** [comment]
I can help with french.

**Comment by Ugface-TurboWarb** [comment]
> We're looking for people who are fluent in English and at least one other language to help translate TurboWarp into languages other than English.
> 
> If you're interested, please read the [contributing guidelines](https://github.com/TurboWarp/translations/blob/master/CONTRIBUTING.md) to learn how to contribute. Comment here or open an issue if you have questions.
> 
> Thank you!

**Comment by Ugface-TurboWarb** [comment]
I can do French and some Spanish & Latin

**Comment by GarboMuffin** [comment]
@Ugface-TurboWarb Review https://github.com/TurboWarp/translations/pull/14, maybe add suggestions for ones that are still `null`

**Comment by Ugface-TurboWarb** [comment]
Like what GarboMuffin?

**Comment by Remixsuper-on-scratch** [comment]
Hi ! I can translate in french but i know how to program only in scratch

**Comment by Dieforrobux** [comment]
Well, If you want to talk with garbomuffin. I don't know how too do that. But i know how to tranlaste some of turbowarp . do ya know how 

______________________________________________________________________

### _**If you help turbowarp. We can help Garbomuffin. You can help turbowarp but don't translate from a website.**_

Lets get into the turbowarp. Tranlaste and help turbowarp

🥇 :(

**Comment by Dieforrobux** [comment]
For Tajik. Put TurboWarp як намуди Scratch аст, ки лоиҳаҳоро ба JavaScript тартиб медиҳад, то онҳо дар ҳақиқат зуд кор кунанд. Онро бо ворид кардани ID лоиҳа ё URL дар боло ё интихоби лоиҳаи дар поён овардашуда санҷед. as TurboWarp is a Scratch mod that compiles projects to JavaScript to make them run really fast. Try it out by inputting a project ID or URL above or choosing a featured project below.

**Comment by EBXavier** [comment]
I'm EBX2. https://scratch.mit.edu/users/EBX2

**Comment by Jordanjopa1** [comment]
It seems... that i now useless here for Italian.

**Comment by GarboMuffin** [comment]
You can still help by reviewing all of the translation and opening issues/submitting PRs for anything that seems incorrect

**Comment by Jordanjopa1** [comment]
> @GarboMuffin https://scratch.mit.edu/projects/446888444 < ALL the translitions here
> Loading screen ⬇
> 
> Loading scripts: Caricamento degli script
> This may take a while...: Ci vorrà un po di tempo...
> Troubleshooting: Risoluzione dei problemi

**Comment by sargent-coding** [comment]
~~Use Google Translate~~

**Comment by BCM28** [comment]
Hmm... I know some Chinese. maybe I can help?

**Comment by GarboMuffin** [comment]
@BCM28 https://github.com/TurboWarp/translations/blob/master/CONTRIBUTING.md

**Comment by sargent-coding** [comment]
Try using [MyMemory](https://mymemory.translated.net/). It's really good.

**Comment by Jordanjopa1** [comment]
> @GarboMuffin https://scratch.mit.edu/projects/446888444 < ALL the translitions here
> Loading screen ⬇
> 
> Loading scripts: Caricamento degli script
> This may take a while...: Ci vorrà un po di tempo...
> Troubleshooting: Risoluzione dei problemi

Then, i will ushare the project. Later

**Comment by Ugface-TurboWarb** [comment]
> ~Use Google Translate~

Do NOT use translate, it is a persons biggest enemy. It translates some words correctly but not all!

**Comment by Jordanjopa1** [comment]
> You can still help by reviewing all of the translation and opening issues/submitting PRs for anything that seems incorrect

Uh, i found a translition problem

**Comment by GarboMuffin** [comment]
@Jordanjopa1 if there's something wrong with one of the translations -> https://github.com/TurboWarp/translations/issues/new

**Comment by dayfinGitHub** [comment]
Hello GraboMuffin! I would love to help and translate this into German is possible!

**Comment by GarboMuffin** [comment]
@dayfinGitHub https://github.com/TurboWarp/translations/blob/master/CONTRIBUTING.md

**Comment by PetitScratchCat** [comment]
i am french

**Comment by Ugface-TurboWarb** [comment]
All into German - thanks to @Jordanjopa1 for the layout and bensound.com for the music

https://scratch.mit.edu/projects/448727515/

**Comment by Dieforrobux** [comment]
> > ~Use Google Translate~
> 
> Do NOT use translate, it is a persons biggest enemy. It translates some words correctly but not all!

I Didn't use google translate

**Comment by AnnoyedArt1256** [comment]
> Do NOT use

I didn't use translate

**Comment by Jordanjopa1** [comment]
> All into German - thanks to @Jordanjopa1 for the layout and bensound.com for the music
> 
> https://scratch.mit.edu/projects/448727515/

Is not from bendsound X3 thank you!

**Comment by Dieforrobux** [comment]
> @GarboMuffin i will finish it tomorrow. I used Google to translate BUT i fixed ALL the problems in the translitions, i'm sure that the translition doesn't have any problems...

bud he said no computer

**Comment by Dieforrobux** [comment]
H'lo?

**Comment by GarboMuffin** [comment]
Translations are currently on hold right now.

I'm planning to follow a certain browser extension and move to a platform like Transifex soon.

**Comment by Dieforrobux** [comment]
okay.

**Comment by littlebunny06** [comment]
Aight, got it

**Comment by Dieforrobux** [comment]
Hello, I am back!

Task 1 - [Help Turbowarp!] 

______________________

Will be posting tasks here. 1 by 1.

**Comment by Dieforrobux** [comment]
- [ ]

**Comment by Dieforrobux** [comment]
> > @GarboMuffin i will finish it tomorrow. I used Google to translate BUT i fixed ALL the problems in the translitions, i'm sure that the translition doesn't have any problems...
> 
> bud he said no translate computer

**Comment by Dieforrobux** [comment]
[https://gitjub.com/TurboWarp/translations/issues/1](url)

**Comment by GarboMuffin** [comment]
We've moved to Transifex to manage translations.

https://github.com/TurboWarp/translations/blob/master/CONTRIBUTING.md

If you have questions, https://github.com/TurboWarp/translations/discussions/new
