### ISSUE TITLE
Move to a more proper translation platform

### ISSUE THREAD

**Issue by GarboMuffin** [TurboWarp/translations#10]
This whole GitHub PR thing is an interesting experiment, but it obviously has some shortcomings

Moving to a platform like crowdin that is actually designed for this might be a good idea

**Comment by Dieforrobux** [comment]
Hmmm, What do you mean

_____

Sorry if i not reponding to comments Just right checking github some times. 😟 and i am 🤐

**Comment by Dieforrobux** [comment]
___

Not sad

**Comment by FISHARMNIC** [comment]
so can I still translate here?

**Comment by GarboMuffin** [comment]
yes

**Comment by Dieforrobux** [comment]
Do we move?

**Comment by GarboMuffin** [comment]
Migration to Transifex happening this weekend
