### ISSUE TITLE
Complete transifex migration

### ISSUE THREAD

**Issue by GarboMuffin** [TurboWarp/translations#21]
- [x] tell everyone who opened a PR that we moved,  close all PRs
 - [x] make the new contributing guide not suck
 - [x] wait for us to not be on the front page of Scratch...
 - [ ] put a call to action at the top of the website to get things a lot of eyes very quickly
 - [ ] sneaky advertising through other avenues

**Comment by Dieforrobux** [comment]
Ok so we go to transifex,so what's it called?

**Comment by Dieforrobux** [comment]
But i just requested.

**Comment by Dieforrobux** [comment]
kk
