### ISSUE TITLE
I have requested

### ISSUE THREAD

**Issue by Dieforrobux** [TurboWarp/translations#22]
**Transifex username:** Dieforrobux

**Languages you want to translate into:** Ghana

**Comment by Dieforrobux** [comment]
I reopened this, But what i do i do?

**Comment by GarboMuffin** [comment]
What language is "Ghana"? I can't find a language called that and apparently English is the primary language spoken there. Is it in Scratch itself, and if so, what do they call it?

**Comment by Dieforrobux** [comment]
> What language is "Ghana"? I can't find a language called that and apparently English is the primary language spoken there. Is it in Scratch itself, and if so, what do they call it?

Well. It seems it comes from a country,humans, And my parents. I may not have found this on scratch neiter turbowarp. I don't really react to this "Changing languages." Apparently, I say its Probably (99.9%) Called Ghanaian language.

**Comment by Dieforrobux** [comment]
> What language is "Ghana"? I can't find a language called that and apparently English is the primary language spoken there. Is it in Scratch itself, and if so, what do they call it?

Actually. Ghana is not at the Scratch website. But is it possible that i can tell my parents if they can help and try to covert it in a real language?

**Comment by Dieforrobux** [comment]
waittttttttt

**Comment by GarboMuffin** [comment]
accepted request to join french

**Comment by Dieforrobux** [comment]
> accepted request to join french

Accept: True.
