### ISSUE TITLE
Portuguese translation request

### ISSUE THREAD

**Issue by Fupicat** [TurboWarp/translations#28]
**Transifex username:** Fupicat

**Scratch username (optional; may be used to credit you later):** Fupicat

**Languages you want to translate into:** Portuguese and Portuguese (Brazil)

**Comment by GarboMuffin** [comment]
Sent invitations

**Comment by GarboMuffin** [comment]
Is the different between Portuguese and Portuguese (Brazil) large enough to justify having to translate everything twice, or should it all be merged into one Portuguese?

**Comment by Fupicat** [comment]
There are some differences in vocabulary, but not in grammar. The
difference is not enough to the point where most other programs have only
one, I think you could merge them unless a native speaker wants to
translate it.

Em ter, 15 de dez de 2020 17:05, Thomas Weber <notifications@github.com>
escreveu:
