### ISSUE TITLE
How do code

### ISSUE THREAD

**Issue by Dieforrobux** [TurboWarp/translations#3]
If you want to put it there. Do you have to code or not. 

### **_How to do code_**

This is a Issues i can't find out. If you can repond. Great. But i need help.

You can check my scratch profile and learn more.

We need help of not only  English . Lets help turbowarp get great and good again!

**Comment by GarboMuffin** [comment]
If you want to contribute, read https://github.com/TurboWarp/translations/blob/master/CONTRIBUTING.md

No coding knowledge should be required

**Comment by Dieforrobux** [comment]
Ok. Do i close the issue?
