### ISSUE TITLE
Issue: Join translation team

### ISSUE THREAD

**Issue by diaowinner** [TurboWarp/translations#33]
**Transifex username:** diaowinner

**Scratch username (optional; may be used to credit you later):** diaowinner

**Languages you want to translate into:** zh_CN

**Comment by GarboMuffin** [comment]
It can't seem to find you, are you sure that's your Transifex username?

![image](https://user-images.githubusercontent.com/33787854/103258460-a5a6fa00-495a-11eb-8a24-c9756dfb0df0.png)

**Comment by diaowinner** [comment]
> It can't seem to find you, are you sure that's your Transifex username?
> 
> ![image](https://user-images.githubusercontent.com/33787854/103258460-a5a6fa00-495a-11eb-8a24-c9756dfb0df0.png)

[Yes.](https://www.transifex.com/user/profile/diaowinner/)

**Comment by GarboMuffin** [comment]
Sent invitation

**Comment by GarboMuffin** [comment]
Scratch has two Chinese variants, zh_CN and zh_TW. Are these essentially the same or is there a significant enough difference to translate everything twice?

**Comment by diaowinner** [comment]
zh_CN and zh_TW are diffirent.
|en|zh_CN|zh_TW|
|-|-|-|
|Project|项目|專案|

BTW, the characters are also different, like 历——歷、曆.
