### ISSUE TITLE
Subscribe

### ISSUE THREAD

**Issue by Dieforrobux** [TurboWarp/translations#34]
Hello, Today i was looking on the turbowarp translations and found this: https://github.com/TurboWarp/translations/issues/27#event-4162851641, And it had news, Came in december 2020, And closed 3 Days ago, (Jan 6 2021), I got confused and decided to ask for help to see if you posted it, So i am guessed that we should Subscribe to that Issue or every single Issue? Even though this isn't helping for translations, I just want a answer. @GarboMuffin

**Comment by GarboMuffin** [comment]
That issue  was made when the translation process was in an experimental state and I wasn't really sure how this would work. The situation has changed since then.

**Comment by Dieforrobux** [comment]
@GarboMuffin Thanks for the Information. I may recheck alot of times.
