### ISSUE TITLE
Norwegian

### ISSUE THREAD

**Issue by TheNumber100IsTaken** [TurboWarp/translations#44]
**Transifex username: TheNumber100IsTaken ** 

**Scratch username (optional; may be used to credit you): ThisFeelsScratchy ** 

**Language: Norwegian**

**Comment by GarboMuffin** [comment]
Does Scratch have a Norwegian translation? I can't seem to find it, maybe I'm just missing something

**Comment by GarboMuffin** [comment]
Scratch has multiple "Norweigan" languages:

Norsk Bokmål
Norsk Nynorsk

Which one do you want to translate (or both)?

**Comment by TheNumber100IsTaken** [comment]
I want to translate Norsk Bokmål.

**Comment by GarboMuffin** [comment]
invited
