### ISSUE TITLE
Dutch

### ISSUE THREAD

**Issue by TheBugCoder** [TurboWarp/translations#45]
**Transifex username: TheBugCoder** 

**Scratch username (optional; may be used to credit you): TheBugCoder** 

**Languages you want to translate into: Dutch**

**Comment by GarboMuffin** [comment]
It can't find your transifex account, did you mark it as public?

![image](https://user-images.githubusercontent.com/33787854/115077730-25ce7c80-9ec4-11eb-847b-fa4dde266e98.png)

**Comment by TheBugCoder** [comment]
No, I didn't . Sorry! Now it is. :D

Op vr 16 apr. 2021 om 21:58 schreef GarboMuffin ***@***.***>:

**Comment by GarboMuffin** [comment]
invited

**Comment by TheBugCoder** [comment]
Thanks!

Op zo 18 apr. 2021 om 17:43 schreef GarboMuffin ***@***.***>:
