### ISSUE TITLE
Hindi is not there in the languages. 

### ISSUE THREAD

**Issue by Mr-Anonymous75** [TurboWarp/translations#9]
I'm not sure that I can spot Hindi in the languages.md file...

**Comment by GarboMuffin** [comment]
Do you know if Scratch itself has a Hindi translation?

**Comment by Mr-Anonymous75** [comment]
> Do you know if Scratch itself has a Hindi translation?

Oh yeah, there isn't...

**Comment by Dieforrobux** [comment]
This got closed...

**Comment by GarboMuffin** [comment]
Closing as this is something that must be addressed by Scratch.
